config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :teacher_profiles
  resources :schools
  resources :student_profiles
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  root 'pages#home'
  get 'pages/home'
  patch 'connect_your_school', to: 'teacher_profiles#connect_your_school'
  get 'pages/admin'

  get 'pages/contact'

  devise_for :users

end

app/models/teacher_profile.rb
class TeacherProfile < ActiveRecord::Base
  belongs_to :school
  belongs_to :user

  # validates :first_name, :last_name, :contact_phone, :bio, presence: true
  def profile_complete?
		self.contact_phone && self.bio && self.first_name
	end
  def full_name
		self.first_name.to_s + ' ' + self.last_name.to_s
	end
end

app/controllers/teacher_profiles_controller.rb
class TeacherProfilesController < ApplicationController
  before_action :set_teacher_profile, only: [ :show, :edit, :update, :destroy]

  def connect_your_school
    @teacher_profile = current_user.teacher_profile
    @teacher_profile.update_attributes(school_id: params[:school])
    redirect_to root_path
  end
  # GET /teacher_profiles
  # GET /teacher_profiles.json
  def index
    @teacher_profiles = TeacherProfile.all
  end

  # GET /teacher_profiles/1
  # GET /teacher_profiles/1.json
  def show
    if @teacher_profile.school
      @school = @teacher_profile.school
    end
  end

  # GET /teacher_profiles/new
  def new
    @teacher_profile = TeacherProfile.new
  end

  # GET /teacher_profiles/1/edit
  def edit
  end

  # POST /teacher_profiles
  # POST /teacher_profiles.json
  def create
    @teacher_profile = TeacherProfile.new(teacher_profile_params)
    @teacher_profile.user = current_user
    respond_to do |format|
      if @teacher_profile.save
        format.html { redirect_to @teacher_profile, notice: 'Teacher profile was successfully created.' }
        format.json { render :show, status: :created, location: @teacher_profile }
      else
        format.html { render :new }
        format.json { render json: @teacher_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teacher_profiles/1
  # PATCH/PUT /teacher_profiles/1.json
  def update
    respond_to do |format|
      if @teacher_profile.update(teacher_profile_params)
        format.html { redirect_to @teacher_profile, notice: 'Teacher profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher_profile }
      else
        format.html { render :edit }
        format.json { render json: @teacher_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teacher_profiles/1
  # DELETE /teacher_profiles/1.json
  def destroy
    @teacher_profile.destroy
    respond_to do |format|
      format.html { redirect_to teacher_profiles_url, notice: 'Teacher profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher_profile
      @teacher_profile = TeacherProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_profile_params
      params.require(:teacher_profile).permit(:school_id, :user_id, :first_name, :last_name, :contact_phone, :profile_pic, :bio)
    end
end

app/views/teacher_profiles/_form.html.erb
<%= simple_form_for(@teacher_profile) do |f| %>
  <%= f.error_notification %>

<div class="row">
  <div class="input-field col s6">
    <%= f.input :first_name %>
  </div>
  <div class="input-field col s6">
    <%= f.input :last_name %>
  </div>
</div>
    
<div class="row">
  <div class="input-field col s6">
    <%= f.input :contact_phone %>
  </div>
  <div class="input-field col s6">
    <%= f.input :profile_pic %>
  </div>
</div>

      <div class="row">
        <div class="input-field col s12">
          <textarea  name="teacher_profile[bio]" id="teacher_profile_bio" class="materialize-textarea"></textarea>
          <label for="textarea1">Bio</label>
        </div>
      </div>

    <button class="btn waves-effect waves-light" type="submit" name="action">Create your profile
    <!-- <i class="material-icons">send</i> -->
  </button>

<% end %>

app/views/teacher_profiles/connect_your_school.html.erb
<h2>Connect to your school</h2>



<% if @schools.present? %>
  <%= render @schools %>
<% else %>
  <p>There are no schools containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/teacher_profiles/edit.html.erb
<h1>Editing Teacher Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher_profile %> |
<%= link_to 'Back', teacher_profiles_path %>

app/views/teacher_profiles/index.html.erb
<h1>Listing teacher_profiles</h1>

<table class="table">
    <tr>
      <th>School</th>
      <th>User</th>
      <th>First_name</th>
      <th>Last_name</th>
      <th>Contact_phone</th>
      <th>Profile_pic</th>
      <th>Bio</th>
        <th colspan="3"></th>
    </tr>

  <%= content_tag_for(:tr, @teacher_profiles) do |teacher_profile| %>
    <td><%= teacher_profile.school %></td>
    <td><%= teacher_profile.user %></td>
    <td><%= teacher_profile.first_name %></td>
    <td><%= teacher_profile.last_name %></td>
    <td><%= teacher_profile.contact_phone %></td>
    <td><%= teacher_profile.profile_pic %></td>
    <td><%= teacher_profile.bio %></td>
      <td><%= link_to 'Show', teacher_profile %></td>
    <td><%= link_to 'Edit', edit_teacher_profile_path(teacher_profile), class: 'btn btn-edit' %></td>
    <td><%= link_to 'Delete', teacher_profile, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-destroy' %></td>
  <% end %>
</table>


<div class="form-actions">
  <%= link_to 'New Teacher profile', new_teacher_profile_path, class: 'btn btn-success' %>
</div>

app/views/teacher_profiles/new.html.erb
<h1>Create your teacher profile</h1>

<%= render 'form' %>

<%= link_to 'Cancel', root_path %>

app/views/teacher_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s12 m6">
    <div class="card">
      <div class="card-image">
        <%= cl_image_tag(@teacher_profile.profile_pic, :width => 450, :height => 250, :crop => :thumb, :gravity => :faces) %>
        <span class="card-title"><%= @teacher_profile.full_name %></span>
      </div>
      <div class="card-content">
        
        <h4>Bio</h4>
        <p><%= @teacher_profile.bio ? @teacher_profile.bio : 'No bio given' %></p>
        
        
      </div>
      <div class="card-action">
        <%= link_to 'Edit your profile', edit_teacher_profile_path(@teacher_profile) %>
      </div>
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card">
      <div class="card-content">
        <h4>School</h4>
        <% if @school %>
          
          <p><%= link_to @school.name, school_path(@school) %></p>
        <% else %>
          <p>No school connected
          <a href="/schools" class="btn-floating btn-large waves-effect waves-light right <%= current_user.teacher_profile.school ? 'green' : 'red' %>"><i class="material-icons">add</i></a></p>
          <br>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', schools_path %>
      </div>
    </div>
</div>