config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :teacher_profiles
  resources :schools
  resources :student_profiles
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  root 'pages#home'
  get 'pages/home'
  patch 'connect_your_school', to: 'teacher_profiles#connect_your_school'
  get 'pages/admin'

  get 'pages/contact'

  devise_for :users

end

app/models/student_profile.rb
class StudentProfile < ActiveRecord::Base
	belongs_to :user

	mount_uploader :profile_pic, ProfilePicUploader

	def full_name
		self.first_name.to_s + ' ' + self.last_name.to_s
	end

	def complete?
		self.address_line_1 && self.contact_number && self.bio && self.first_name
	end

	def has_children_check?
		self.working_with_children_number
	end
end

app/controllers/student_profiles_controller.rb
class StudentProfilesController < ApplicationController
  before_action :set_student_profile, only: [:show, :edit, :update, :destroy]

  # GET /student_profiles
  # GET /student_profiles.json
  def index
    @student_profiles = StudentProfile.all
  end

  # GET /student_profiles/1
  # GET /student_profiles/1.json
  def show
  end

  # GET /student_profiles/new
  def new
    @student_profile = StudentProfile.new
  end

  # GET /student_profiles/1/edit
  def edit
  end

  # POST /student_profiles
  # POST /student_profiles.json
  def create
    @student_profile = StudentProfile.new(student_profile_params)
    @student_profile.user == current_user
    respond_to do |format|
      if @student_profile.save
        format.html { redirect_to @student_profile, notice: 'Student profile was successfully created.' }
        format.json { render :show, status: :created, location: @student_profile }
      else
        format.html { render :new }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_profiles/1
  # PATCH/PUT /student_profiles/1.json
  def update
    respond_to do |format|
      if @student_profile.update(student_profile_params)
        format.html { redirect_to @student_profile, notice: 'Student profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_profile }
      else
        format.html { render :edit }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_profiles/1
  # DELETE /student_profiles/1.json
  def destroy
    @student_profile.destroy
    respond_to do |format|
      format.html { redirect_to student_profiles_url, notice: 'Student profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_profile
      @student_profile = StudentProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_profile_params
      params.require(:student_profile).permit(:first_name, :last_name, :address_line_1, :address_line_2, :suburb, :postcode, :state, :website_url, :contact_number, :degree, :institution, :working_with_children_number, :profile_pic, :induction, :bio)
    end
end

app/views/student_profiles/_form.html.erb
<%= simple_form_for(@student_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :address_line_1 %>
    <%= f.input :address_line_2 %>
    <%= f.input :suburb %>
    <%= f.input :postcode %>
    <%= f.input :state %>
    <%= f.input :website_url %>
    <%= f.input :contact_number %>
    <%= f.input :degree %>
    <%= f.input :institution %>
    <%= f.input :working_with_children_number %>
    <%= f.input :profile_pic %>
    <%= f.input :induction %>
    <%= f.input :bio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/student_profiles/edit.html.erb
<h1>Editing Student Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_profile %> |
<%= link_to 'Back', student_profiles_path %>

app/views/student_profiles/index.html.erb
<h1>Listing student_profiles</h1>

<table class="table">
    <tr>
      <th>First_name</th>
      <th>Last_name</th>
      <th>Address_line_1</th>
      <th>Address_line_2</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Website_url</th>
      <th>Contact_number</th>
      <th>Degree</th>
      <th>Institution</th>
      <th>Working_with_children_number</th>
      <th>Profile_pic</th>
      <th>Induction</th>
      <th>Bio</th>
        <th colspan="3"></th>
    </tr>

  <%= content_tag_for(:tr, @student_profiles) do |student_profile| %>
    <td><%= student_profile.first_name %></td>
    <td><%= student_profile.last_name %></td>
    <td><%= student_profile.address_line_1 %></td>
    <td><%= student_profile.address_line_2 %></td>
    <td><%= student_profile.suburb %></td>
    <td><%= student_profile.postcode %></td>
    <td><%= student_profile.state %></td>
    <td><%= student_profile.website_url %></td>
    <td><%= student_profile.contact_number %></td>
    <td><%= student_profile.degree %></td>
    <td><%= student_profile.institution %></td>
    <td><%= student_profile.working_with_children_number %></td>
    <td><%= student_profile.profile_pic %></td>
    <td><%= student_profile.induction %></td>
    <td><%= student_profile.bio %></td>
      <td><%= link_to 'Show', student_profile %></td>
    <td><%= link_to 'Edit', edit_student_profile_path(student_profile), class: 'btn btn-edit' %></td>
    <td><%= link_to 'Delete', student_profile, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-destroy' %></td>
  <% end %>
</table>


<div class="form-actions">
  <%= link_to 'New Student profile', new_student_profile_path, class: 'btn btn-success' %>
</div>

app/views/student_profiles/new.html.erb
<h1>New Student Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', student_profiles_path %>

app/views/student_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s12 m6">
    <div class="card">
      <div class="card-image">
        <%= cl_image_tag(@student_profile.profile_pic, :width => 450, :height => 250, :crop => :thumb, :gravity => :faces) %>
        <span class="card-title"><%= @student_profile.full_name %></span>
      </div>
      <div class="card-content">
        <h4>Bio</h4>
        <p><%= @student_profile.bio.nil? ? @student_profile.bio : 'No bio given' %></p>
        <p><strong>Website/Blog: </strong><a href="<%= @student_profile.website_url %>" target="_blank"><%= @student_profile.website_url %></a></p>
        
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_student_profile_path(@student_profile) %>
      </div>
    </div>
    <div class="card">
      <div class="card-content">
        <h4>References</h4>
        <p>No references yet
        </p>
      </div>
      <div class="card-action">
        <%= link_to 'Apply for a project', edit_student_profile_path(@student_profile) %>
      </div>
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card">
      <div class="card-content">
        <h4>Requirements</h4>
        <p>
          <strong>Working with children number:</strong>
          <%= @student_profile.working_with_children_number %>
        </p>

        <p>
          <strong>Induction:</strong>
          <%= @student_profile.induction %>
        </p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_student_profile_path(@student_profile) %>
      </div>
    </div>
    <div class="card">
      <div class="card-content">
        
          <h4>Study</h4>
          <p><strong>University/College: </strong> <%= @student_profile.institution %></p>
          <p><strong>Degree: </strong> <%= @student_profile.degree %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_student_profile_path(@student_profile) %>
      </div>
    </div>
    <div class="card">
      <div class="card-content">
        
        <h4>Contact details </h4>
        <p>(not public)</p>
        <div class="row">
          <div class="col s12 m6">
            <h5>Address</h5>
            <p>
              <%= @student_profile.address_line_1 %><br>
              <% unless @student_profile.address_line_2.empty? %>
                <%= @student_profile.address_line_2 %><br>
              <% end %>
              <%= @student_profile.suburb.to_s + ' ' + @student_profile.state.to_s + ' ' + @student_profile.postcode.to_s %><br>
            </p>
          </div>
          <div class="col s12 m6">
            <h5>Phone</h5>
            <p><%= @student_profile.contact_number %></p>
          </div>
        </div>
      </div>
        <div class="card-action">
        <%= link_to 'Edit', edit_student_profile_path(@student_profile) %>
      </div>
    </div>
  </div>

</div>