config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :teacher_profiles
  resources :schools
  resources :student_profiles
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  root 'pages#home'
  get 'pages/home'
  patch 'connect_your_school', to: 'teacher_profiles#connect_your_school'
  get 'pages/admin'

  get 'pages/contact'

  devise_for :users

end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :teacher_profiles
	
	geocoded_by :school_data
	after_validation :geocode

	def school_data
		[name, street_address_1, street_address_2, suburb, state, postcode, country].compact.join(', ')
	end

	def self.search(search)
	  where("name LIKE ?", "%#{search}%")
	end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
    if params[:search]
      @schools = School.search(params[:search]).order("created_at DESC")
    else
      @schools = School.all.order('created_at DESC')
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :street_address_1, :street_address_2, :suburb, :state, :postcode, :country, :acara_school_id, :school_type)
    end
end

app/views/schools/_form.html.erb
<%= simple_form_for(@school) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :street_address_1 %>
    <%= f.input :street_address_2 %>
    <%= f.input :suburb %>
    <%= f.input :state %>
    <%= f.input :postcode %>
    <%= f.input :country %>
    <%= f.input :acara_school_id %>
    <%= f.input :school_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>
<%= form_tag(schools_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Find your school" %>
  <%= submit_tag "Search" %>
<% end %>

<table class="table">
    <tr>
      <th>Name</th>
      <th>Suburb</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>

  <%= content_tag_for(:tr, @schools) do |school| %>
    <td><%= link_to school.name, school %></td>
    <td><%= school.suburb %></td>
    <td><%= school.state %></td>
    <td><%= school.school_type %></td>
    <td><%= link_to 'Connect', connect_your_school_path(school: school.id), method: :patch, class: 'btn btn-edit' %></td>
  <% end %>
</table>


<div class="form-actions">
  <%= link_to 'New School', new_school_path, class: 'btn btn-success' %>
</div>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Street address 1:</strong>
  <%= @school.street_address_1 %>
</p>

<p>
  <strong>Street address 2:</strong>
  <%= @school.street_address_2 %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @school.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @school.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @school.postcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @school.country %>
</p>

<p>
  <strong>Acara school:</strong>
  <%= @school.acara_school_id %>
</p>

<p>
  <strong>School type:</strong>
  <%= @school.school_type %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>